# iShop - https://www.spigotmc.org/resources/ishop.84555/
# The block you want to open the shop GUI
# Shop GUI will be activated only by left or right click
shopBlock: 'minecraft:barrel'

# The block you want to open the stock GUI
# Stock GUI will be activated only by left clicking
stockBlock: 'minecraft:end_portal_frame'

# Allows the use of shop blocks. Setting to false will disable players using specified shop block to open shop GUI
# WARNING: Setting to false will allow breaking of existing shop blocks without deleting shop!
enableShopBlock: true

# Enable more than 1 shop block adding unlimited blocks listed below if true
# WARNING: Removing previously set blocks from this list will allow breaking of existing shop blocks without deleting shop!
multipleShopBlocks: false
shopBlockList:
  - minecraft:chest
  - minecraft:crafting_table

# Allows the use of stock blocks. Setting to false will disable players using specified stock block to open stock GUI
enableStockBlock: true

# Enable more than 1 stock block adding unlimited blocks listed below if true
multipleStockBlocks: false
stockBlockList:
  - minecraft:ender_chest
  - minecraft:jukebox

# Disable trading of listed items below if true
disabledItems: true
disabledItemsList:
  - TNT
  - BEDROCK

# Disable creating shops in worlds listed below if true
disableShopInWorld: false
disabledWorldList:
  - world_nether
  - world_the_end

# This enables admin shops that don't need stock. Created by typing /shop adminshop, requires ishop.admin permission
enableAdminShop: false

# Set player head for admin shops when listing using UUID. Default is 00000000-0000-0000-0000-000000000000
adminPlayerHeadShops: 00000000-0000-0000-0000-000000000000

# Enable clickable chest item in self owned shop gui that will access stock
enableStockAccessFromShopGUI: false

# Allows players to access the stock GUI by typing /shop stock
# Players with ishop.stock permission will bypass if disabled
enableStockCommand: false

# Number of pages to have in the stock GUI
stockPages: 2

# Enable sending of messages when players have purchased or sold item(s) from shops
enableShopNotifications: true

# Enable sending of missed sold item(s) from shops by using command /shop sold
enableShopSoldMessage: true

# Enable saving ALL shop sold messages instead of only messages while player is offline
enableSavingAllShopSoldMessages: true

# Enable sending of message when player connects if items have been sold while offline
enableSoldNotificationOnJoin: true

# Only send sold notification 1 time when players first connects until they use /shop sold clear or server restarts
onlyNotifySoldOnceUntilClear: true

# Delay time in seconds after connecting to notify player of '/shop sold'
soldNotificationsDelayTime: 5

# Automatically clear shop sold list when player reaches end of list
autoClearSoldListOnLast: false

# Enable sending of messages to shop owners if item(s) are out of stock when players try to purchase
enableOutOfStockMessages: true

# Time in seconds before shop owner receives another message about being out of stock when someone tries to buy item(s)
noStockCooldown: 600

# Require player to own at least 1 shop to access stock
mustOwnShopForStock: false

# Amount of money needed to create a shop
# Set to 0 to disable
createCost: 0.0

# Amount of money returned when deleting a shop
# Set to 0 to disable
returnAmount: 0.0

# Amount of days a player is inactive before deleting their shops
# Set to 0 to disable
maxInactiveDays: 14

# List of player UUID's that will be exempt from shops expiring if maxInactiveDays is set above 0
exemptExpiringShops:
  - 00000000-0000-0000-0000-000000000000

# Delete block that the shop is located at when deleting a shop
deleteBlock: false

# Show particle effects on active shop blocks
showParticles: true

# Set whether you want to use permission nodes or not
# Setting to false will allow any player to create a shop up to defaultShopLimit
# Set to true if you have a permission plugin
usePermissions: false

# Only works if usePermissions is set to false
# If it's set to true, then you'll need to edit the limit via permission nodes for example; ishop.create.limit.5
# Set to -1 to disable shop limit
defaultShopLimit: 5

# Allow everyone to remotely manage their own player shops using "/shop manage <id>" command
remoteManage: false

# Allow everyone to use "/shop view <id>" command to view other players shop remotely
remoteShopping: false

# Allow everyone to use "/shop list <player>" command to view full list of given players shops with location
publicListCommand: false

# Allow everyone to use "/shop shops" command to view all found player shops
publicShopListCommand: true

# This will show admin shops when using "/shop shops" -- Requires server restart if config option changed!
adminShopPublic: false

# Setting this to false will hide shops that player owns when using command "/shop shops"
publicShopListShowsOwned: false

# Allow shop owners and admins to place item frames and signs on shop blocks when sneaking
placeItemFrameSigns: true

# Setting to true will protect shop blocks from explosions
protectShopBlocksFromExplosions: true

# Delay loading of shops database in seconds. This is useful if you have shops in custom worlds that take time to load during server startup
# WARNING: During load delay time, shop & stock blocks will NOT be protected! Default is 0 for no delay
shopsDatabaseLoadDelay: 0

# Set a range limit stock block(s) must be within player owned shop block(s) distance to access stock inventory
# Default is 0 for disabled
stockRangeLimitFromShop: 0

# Set to true if you would like '/shop stock' command range limit to be enforced using stockRangeLimitFromShop distance
stockRangeLimitUsingCommand: false

# Customizable Messages
adminShop: "Магическая торговая ячейка #%id"
adminShopDisabled: "&cМагические торговые ячейки отключены!"
broadcastOff: "⚖ Уведомления выключены"
broadcastOn: "⚖ Уведомления включены"
buy: "&f⚖ Куплено&8 %in &fза&8 %out&f."
buyAction: "КУПИТЬ"
buyTitle: "Продаем за"
buyTitle2: "Продаем за"
createShopTitle: "Создание торговой ячейки"
deleteTitle: "&cУДАЛИТЬ"
createTitle: "&aСОЗДАТЬ"
disabledShopBlock: "⚖ Невозможно создать местоположение магазина, если блоки торговой ячейки отключены!"
existingShop: "⚖ Невозможно создать торговую ячейку там, где уже находится торговая ячейка!"
foundShops: "⚖ Найдено&a %shops &6торговых точек у игрока:&a %p"
location: "⚖ Торговая ячейка&a %id находится XYZ: "
noItems: "&f⚖ Недостаточно ресурсов для торговли."
noMoney: "&f⚖ У тебя нет достаточно денег, чтобы создать торговую ячейку. Нужно хотя бы &o$"
noPermissions: "&fНеизвестная команда О_о"
noPlayerFound: "⚖ Игрок не найден!"
noPlayerShop: "⚖ Имя игрока не существует! Что ты от меня хочешь?!"
noRemoteManage: "⚖ Удаленное управление отключено!"
noRemoteShops: "⚖ Удаленное управление отключено!"
normalShop: "Торговая ячейка %player% #%id"
noShopFound: "⚖ Торговых ячеек не найдено!"
noShopStock: "⚖ Склад недоступен, так как вы ничего не продаете."
noStock: "⚖ Товар отсутствует на складе."
noStockNotify: "⚖ В твоей торговой ячейке закончился товар: (%s)"
page: "Страница"
playerInventoryFull: "⚖ Ваш инвентарь полон. Покупка отменена."
playerShopCreated: "⚖ Создали торговую ячейку %p"
reload: "&f⚖ Перезагрузили конфигурацию и надеемся, что ничего не сломали."
sell: "&f⚖ %p продано &8 %in &f за&8 %out&f."
sellTitle: "Продаем"
sellTitle2: "Продаем"
shopBusy: "⚖ Торговая ячейка в настоящее время занята, попробуй еще раз в ближайшее время!"
shopCreated: "⚖ Торговая ячейка была создана!"
shopDeleted: "⚖ Торговая ячейка была удалена!"
shopIDDeleted: "⚖ Торговая ячейка %id была удалена!"
shopIntegerError: "⚖ Номер торговой ячейки должен быть целым числом больше 0!"
shopLimit: "&f⚖ Наши юристы сказали, что создавать так много торговых ячеек нельзя."
shopNotOwned: "&f⚖ Это не твоя торговую точку и редактировать ее нельзя :("
stockCommandDisabled: "⚖ Команда /shop stock отключена!"
stockTitle: "Склад торговой ячейки"
targetMismatch: "⚖ Сначала установи бочку, после чего напиши эту команду."
clickManage: "&eУправление"
clickShop: "&eТорговая ячейка"
listAdminShop: "⚖ Все магические торговые ячейки:"
noAdminShopsFound: "⚖ Не найдено магических торговых ячеек!"
noShopBlock: "&cERROR GoodTrade: shopBlock cannot be empty! Reverting to default"
noStockBlock: "&cERROR GoodTrade: stockBlock cannot be empty! Reverting to default"
notPlayer: "⚖ Только игроки могут использовать этму команду..."
shopListTitle: "Список торговых ячеек"
shopNumber: "Торговая ячейка %player #%id"
shopListDisabled: "⚖ Список торговых ячеек отключен!"
adminShopNumber: "Магическая торговая ячейка #%id"
noStockButton: "Товар отсутствует на складе"
stockIntegerError: "&cERROR GoodTrade: Stock page must be an integer greater than 0!"
soldClear: "⚖ Список проданных товаров магазина был очищен"
soldCommandDisabled: "⚖ Команда /shop sold отключена!"
soldHeader: "⚖ Пока тебя не было, мы продали товары (Страница %p):"
soldIntegerError: "&cERROR GoodTrade: Sold page must be an integer greater than 0!"
soldJoinNotify: "&fВведи &a/shop sold&f для просмотра проданных товаров или &a/shop sold clear &fдля очистки."
soldNothing: "⚖ Мы ничего не продали, пока тебя не было."
soldPages: "&7Страница %p"
soldPagesNext: " &7>> &6Дальше"
soldPagesPrevious: "&6Назад &7<< "
disabledWorld: "⚖ Этот мир опасен и никто не посещает его. Мне не нужна здесь торговая ячейка..."
listOutOfStock: "&6Listing shops out of stock:"
notOutOfStock: "&aNo shops found that are out of stock!"
outOfStock: "&6Shop&a #%shop Row %row &6is out of stock"
outOfStockRange: "&cYou are too far away from your shop(s) to access stock inventory!"
countAmount: "&aTotal amount of %item found: %amount"
countEmpty: "&cCannot find any %item in stock inventory!"
countError: "&cGiven item to search stock for does not exist!"
outsideRegion: "&cCannot create shop outside of ishop region!"

# Do not edit this!
configVersion: 3.1