name: iShop
main: com.minedhype.ishop.iShop
description: Item trading shops
author: Beez0r, Envel
version: "${project.version}"
api-version: "1.17"
softdepend: [Vault, WorldGuard]
commands:
  ishop:
    description: "/shop"
    aliases: [shop]
