name: GoodTrade
main: com.minedhype.ishop.iShop
description: Item trading shops
author: Beez0r, Envel
version: "${project.version}"
api-version: "1.18"
softdepend: [Vault, WorldGuard]
commands:
  goodtrade:
    description: "/shop"
    aliases: [shop]
